apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: akshaykumart/myapp:latest
        ports:
        - containerPort: 3000
